trigger:
  none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: 'Microsoft Azure Sponsorship 2'
      scriptType: 'FilePath'
      scriptPath: 'ARMTemplate/set-pipelineenvironmenttoken.ps1'
      scriptArguments: ' ResourceGroupName mscloudforretailB2C '
      azurePowerShellVersion: 'latestVersion' 
      
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: '/build'
      azure_static_web_apps_api_token: $(token)